/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9fe",
        "surface-container": "#ededf2",
        "tertiary-fixed": "#ffdbcb",
        "background": "#f9f9fe",
        "on-primary-fixed": "#001b3e",
        "surface-variant": "#e2e2e7",
        "on-secondary-fixed": "#002107",
        "on-secondary-container": "#00732a",
        "outline": "#717786",
        "tertiary-container": "#c25300",
        "on-surface": "#1a1c1f",
        "inverse-surface": "#2e3034",
        "surface-container-low": "#f3f3f8",
        "on-tertiary-fixed": "#341100",
        "tertiary-fixed-dim": "#ffb691",
        "secondary-container": "#6ffb85",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#793100",
        "surface-container-highest": "#e2e2e7",
        "secondary": "#006e28",
        "on-secondary-fixed-variant": "#00531c",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dade",
        "outline-variant": "#c0c6d6",
        "primary-fixed": "#d6e3ff",
        "surface": "#f9f9fe",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "tertiary": "#9a4100",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "secondary-fixed": "#72fe88",
        "secondary-fixed-dim": "#53e16f",
        "on-surface-variant": "#414754",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "inverse-primary": "#aac7ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f0f5",
        "surface-container-high": "#e8e8ed",
        "primary": "#005ab3",
        "surface-tint": "#005db8",
        "on-background": "#1a1c1f",
        "primary-container": "#0073e0",
        "primary-fixed-dim": "#aac7ff",
        "on-primary-fixed-variant": "#00468d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
